export const TYPOGRAPHY_VARIANTS = [
  "body",
  "hero-name",
  "section-heading",
  "card-heading",
  "project-heading",
  "eyebrow",
  "hero-role",
  "hero-tag",
  "section-body",
  "section-body-strong",
  "nav-logo",
  "floor-btn",
  "button",
  "unit-plate",
  "unit-org",
  "unit-notes",
  "unit-tag",
  "open-sign",
  "project-body",
  "stack-pill",
  "project-link",
  "cert-label",
  "cert-stamp",
  "skill-label",
  "cert-also",
  "intercom-head",
  "buzzer",
  "footer",
] as const;

export const TYPOGRAPHY_COLORS = [
  "sky-deep",
  "sky-warm",
  "block",
  "paper",
  "mist",
  "window",
  "signage",
  "add",
  "del",
  "block-border",
] as const;
